# Define stages of the pipeline
stages:
  - test
  - publish

# Job to run tests
test:
  stage: test
  image: registry.gitlab.com/labequipmentadapterframework/leaf:runner
  before_script:
    - mosquitto -d
    - redis-server --daemonize yes
    - source /venv/bin/activate
    - poetry lock
    - poetry install
    - poetry env info  # Debug Poetry environment
    - poetry show  # Check installed dependencies
  script:
    - poetry show pytest-xdist  # Verify pytest-xdist is installed
    - poetry run pytest tests/ --junitxml=test-reports/report.xml
  artifacts:
    when: always
    reports:
      junit: test-reports/*.xml
    paths:
      - test-reports/
  timeout: 20m


publish:
  stage: publish
  image: python:3.12
  before_script:
    - pip install poetry
    - poetry config pypi-token.pypi "$PYPI_TOKEN"
    - poetry build
  script:
    poetry publish
  only:
    - dev  # restrict to dev branch

