# Define stages of the pipeline
stages:
  - test

# Job to run tests
test:
  stage: test
  image: registry.gitlab.com/labequipmentadapterframework/leaf:runner
  before_script:
    - mosquitto -d # Start mosquitto
    - redis-server --daemonize yes # Start Redis
    - poetry lock
    - poetry install
    - source $(poetry env info --path)/bin/activate
  script:
    - source $(poetry env info --path)/bin/activate
    - poetry lock
    - poetry install
    - pytest tests/ --junitxml=test-reports/report.xml -n auto
  artifacts:
    when: always
    reports:
      junit: test-reports/*.xml
    paths:
      - test-reports/
  timeout: 10m  # Set job timeout (increase if needed for larger test suites)
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .venv/  # Cache the virtual environment (if using virtualenv)
      - requirements.txt  # Cache requirements file
      - __pycache__/  # Cache Python bytecode
