
EQUIPMENT_INSTANCES:
  - equipment:
      adapter: BioLector1
      data:
        instance_id: biolector_devonshire10
        institute: NCL
      requirements:
        write_file: test/tmp.csv
      simulation:
        filename: tests/static_files/biolector1_full.csv
        interval: 10
  - equipment:
      adapter: BioLector1
      data:
        instance_id: test_instance_id
        institute: NCL
      requirements:
        write_file: test/tmp123.csv
OUTPUTS:
  - plugin: MQTT
    broker: localhost
    port: 1883
    username: mcrowther
    password: Radeon12300
    fallback: KEYDB
  - plugin: KEYDB
    host: localhost
    port: 6379
    db: 0
    fallback: FILE
  - plugin: FILE
    filename: local.json
    fallback: null