EQUIPMENT_INSTANCES:
  - equipment:
      adapter: BioLector1
      data:
        instance_id: biolector_manchester4
        institute: MAN
      requirements:
        write_file: tmp/tmp.csv
OUTPUTS:
  - plugin: MQTT
    broker: localhost
    port: 1883
    username: mcrowther
    password: Radeon12300
    fallback: KEYDB

  - plugin: KEYDB
    host: localhost
    port: 6379
    db: 0
    fallback: FILE

  - plugin: FILE
    filename: local.json
    fallback: null