EQUIPMENT_INSTANCES:
  - equipment:
      adapter: HelloWorld
      data:
        instance_id: example_equipment_id1
        institute: example_equipment_institute1
      requirements:
        interval: 1


OUTPUTS:
  - plugin: MQTT
    broker: test.mosquitto.org
    port: 1883
    fallback: KEYDB
  - plugin: KEYDB
    host: localhost
    port: 6379
    db: 0
    fallback: FILE
  - plugin: FILE
    filename: local.json
    fallback: null
